CLIENT := 172.30.1.60

KDIR := ~/sl2c100_kernel_2.6.29_20100622
CMPL := arm-s5pc1xx-linux-gnueabi-
PWD := $(shell pwd)

define copy
scp $(TARGET)/$1 root@$(CLIENT):~/
ssh root@$(CLIENT)
endef

connect:
	ssh root@$(CLIENT)